import Login from "@/components/logins/Login";
import React from "react";

export const metadata = {
  title: "Login to your PayPal account",
  description: "Generated by create next app",
};
function page() {
  return (
    <div className="bg-white">
      <Login />
    </div>
  );
}

export default page;
