import { ToastProvider } from "@/context/ToastContext";
import "./globals.css";
import { AppProvider } from "@/context/appContext";

export const metadata = {
  title: "A Simple and Safer Way to Pay and Get Paid | PayPal US",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ToastProvider>
          <AppProvider>{children}</AppProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
