import "./globals.css";
import { AppProvider } from "@/context/appContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <AppProvider>{children}</AppProvider>
        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
